version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/mixpanel_flutter"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 30
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 30
